<a href="https://colab.research.google.com/github/rivkms/2021_sw_exam/blob/main/2%EC%A3%BC%EC%B0%A8_Numpy_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2주차 Numpy 실습 과제
- 과제를 완성하여 클래스룸에 기한내에 제출합니다.

## 1. Numpy의 속도
- 대용량 계산에서 흔히 사용되는 Numpy는 C로 구현되어 파이썬의 특징인 dynamic typing을 포기하는 대신 성능을 확보했다.

일반적으로 처리 속도는 for loop < list comprehension < numpy이다. 이를 증명하는 프로그램을 작성하시오.

In [ ]:
import numpy as np

iteration = 1000000 # 1,000,000
scalar = 2

# for loop
def loops(scalar, vector):
    result=[]
    for value in vector:
        result.append(value * scalar)
    return result

%timeit loops(scalar, list(range(iteration)))
%timeit # 1. your code here(list comprehension)
%timeit # 2. your code here(numpy)

10 loops, best of 5: 158 ms per loop


ValueError: ignored

## 2. 관절염 환자 데이터 분석
관절염 환자에게 신약을 투여후 염증 수치를 기록한 데이터를 분석한다. 각 데이터는 콤마(,)로 분리되어 있고, 행은 각 환자이며 열은 연속한 날짜별 염증수치를 기록하고 있다.

#### 2-1. 데이터 로딩
1. 다음 파일을 프로그램에 로딩하시오.
- 파일명: lab_inflammation-01.csv

In [ ]:
import numpy as np
data = np.loadtxt('lab_inflammation-01.csv',delimiter = ',',skiprows=1)

#### 2-2. 데이터의 형태 확인
1. 데이터의 shape를 확인하시오.
2. 처음 5행의 데이터 출력하시오.
3. 맨 마지막 행의 데이터 출력하시오.

In [ ]:
data[-1,]
print(data.shape)
print(data)

(59, 40)
[[0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 [0. 0. 2. ... 3. 2. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


4. 각 데이터의 값을 모두 2배로 증가시킨 데이터를 double_data에 저장한 후 5번째 환자의 데이터를 출력하시오.

In [ ]:
double_data=data*2
print(double_data)

[[0. 2. 4. ... 2. 0. 2.]
 [0. 2. 2. ... 4. 2. 2.]
 [0. 0. 4. ... 6. 4. 2.]
 ...
 [0. 2. 2. ... 2. 2. 2.]
 [0. 0. 0. ... 0. 4. 0.]
 [0. 0. 2. ... 2. 2. 0.]]


5. numpy를 이용해 각 데이터의 루트 값을 계산하고 5번째 환자의 데이터를 출력하시오.

#### 2-3. 통계값 확인
1. 모든 데이터 대상으로 최대값, 최소값, 표준편차를 출력하시오.

In [ ]:
print('최대값: ')
print('최소값: ')
print('표준편차: ')

2. 다음 그림을 참조하여 첫번째 환자의 염증수치 최대값을 출력하시오.

<img src='https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FDAfNj%2FbtqDiayg5Bx%2FWyUrFFw50MbkcTDP6PqJF1%2Fimg.png' width=500>

In [ ]:
print('첫번째 환자(patient 0)의 최대 염증수치: ')

3. 각 환자에 대해 가장 높은 염증수치를 기록한 날을 찾으시오(np.argmax(data) 또는 data.argmax에 대한 정보를 찾아서 해결하시오).

4. 첫째날 모든 환자의 염증수치의 평균을 구하시오.

In [ ]:
print('첫째날 모든 환자의 염증수치 평균: ')

## 3. 수학 관련 함수
numpy는 매우 많은 수학관련 함수를 제공하고 있다. numpy 문서(https://numpy.org/doc/1.18/reference/routines.math.html) 탐색을 통해 함수 5개를 선정하고 관련 예제를 작성하시오.

In [ ]:
#1

In [ ]:
#2

In [ ]:
#3

In [ ]:
#4

In [ ]:
#5